on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: executing test
        with:
          script: |
            cd back
            npm run dev 
